<?php
if(!defined('ABSPATH'))exit;
class Hooshid{
 public static function init(){self::ensure_schema();new Hooshid_Books();new Hooshid_AI();new Hooshid_Shortcode();add_action('admin_menu',[__CLASS__,'admin_menu']);add_action('admin_notices',[__CLASS__,'admin_notices']);add_action('admin_init',[__CLASS__,'settings']);add_action('wp_enqueue_scripts',[__CLASS__,'assets']);add_action('admin_enqueue_scripts',[__CLASS__,'admin_assets']);}
 public static function ensure_schema(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$t=$wpdb->prefix.'hooshid_books';$p=$wpdb->prefix.'hooshid_book_pages';if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$t))!==$t||$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$p))!==$p)self::activate();}
 public static function activate(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$t=$wpdb->prefix.'hooshid_books';$p=$wpdb->prefix.'hooshid_book_pages';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE $t (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,grade tinyint unsigned NOT NULL,subject varchar(100) NOT NULL,title varchar(255) NOT NULL,attachment_id bigint(20) unsigned NOT NULL,created_at datetime NOT NULL,PRIMARY KEY(id),KEY grade(grade),KEY subject(subject)) $c;");dbDelta("CREATE TABLE $p (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,book_id bigint(20) unsigned NOT NULL,page_number int unsigned NOT NULL,page_text longtext NULL,PRIMARY KEY(id),UNIQUE KEY book_page(book_id,page_number),KEY book_id(book_id)) $c;");}
 public static function admin_menu(){add_menu_page('هوشید','هوشید','manage_options','hooshid','Hooshid::dashboard','dashicons-welcome-learn-more',30);add_submenu_page('hooshid','تنظیمات','تنظیمات','manage_options','hooshid-settings','Hooshid::settings_page');add_submenu_page('hooshid','کتاب‌ها','کتاب‌ها','manage_options','hooshid-books','Hooshid::books_page');}
 public static function admin_assets($hook){if($hook==='hooshid_page_hooshid-books'||$hook==='toplevel_page_hooshid')wp_enqueue_media();}
 public static function settings(){register_setting('hooshid_settings','hooshid_openai_key',['sanitize_callback'=>'sanitize_text_field']);register_setting('hooshid_settings','hooshid_openai_model',['sanitize_callback'=>'sanitize_text_field']);}
 public static function assets(){wp_register_style('hooshid',HOOSHID_URL.'assets/css/hooshid.css',[],HOOSHID_VERSION);wp_register_script('hooshid',HOOSHID_URL.'assets/js/hooshid.js',[],HOOSHID_VERSION,true);wp_localize_script('hooshid','hooshidData',['rest'=>esc_url_raw(rest_url('hooshid/v1')),'nonce'=>wp_create_nonce('wp_rest'),'pdfWorker'=>'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/5.4.149/pdf.worker.min.mjs']);}
 public static function admin_notices(){if(!current_user_can('manage_options'))return;global $wpdb;$t=$wpdb->prefix.'hooshid_books';$p=$wpdb->prefix.'hooshid_book_pages';if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$t))!==$t||$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$p))!==$p)echo '<div class="notice notice-error"><p>جداول هوشید ساخته نشده‌اند. افزونه را یک‌بار غیرفعال و دوباره فعال کنید.</p></div>';}
 public static function dashboard(){echo '<div class="wrap"><h1>هوشید</h1><p>تخته آموزشی وب، کتاب‌های PDF و دستیار هوش مصنوعی.</p><p>در یک برگه از <code>[hooshid]</code> استفاده کنید.</p></div>';}
 public static function settings_page(){?><div class="wrap"><h1>تنظیمات هوشید</h1><form method="post" action="options.php"><?php settings_fields('hooshid_settings');?><table class="form-table"><tr><th>OpenAI API Key</th><td><input type="password" class="regular-text" name="hooshid_openai_key" value="<?php echo esc_attr(get_option('hooshid_openai_key',''));?>"><p class="description">کلید فقط در سمت سرور استفاده می‌شود.</p></td></tr><tr><th>مدل</th><td><input class="regular-text" name="hooshid_openai_model" value="<?php echo esc_attr(get_option('hooshid_openai_model','gpt-6-luna'));?>"><p class="description">مثلاً gpt-6-luna.</p></td></tr></table><?php submit_button('ذخیره تنظیمات');?></form></div><?php}
 public static function books_page(){$books=Hooshid_Books::all();?><div class="wrap"><h1>کتاب‌ها و درس‌ها</h1><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('hooshid_save_book');?><input type="hidden" name="action" value="hooshid_save_book"><input type="hidden" name="attachment_id" id="hooshid_attachment_id"><table class="form-table"><tr><th>پایه</th><td><select name="grade"><?php for($i=1;$i<=6;$i++)echo '<option value="'.$i.'">پایه '.$i.'</option>';?></select></td></tr><tr><th>درس</th><td><input name="subject" class="regular-text" required placeholder="ریاضی"></td></tr><tr><th>عنوان کتاب</th><td><input name="title" class="regular-text" placeholder="کتاب ریاضی پنجم"></td></tr><tr><th>PDF</th><td><button type="button" class="button" id="hooshid-select-pdf">انتخاب PDF از رسانه</button><span id="hooshid-pdf-name" style="margin-right:10px"></span></td></tr></table><?php submit_button('افزودن کتاب');?></form><hr><h2>کتاب‌های ثبت‌شده</h2><table class="widefat striped"><thead><tr><th>پایه</th><th>درس</th><th>عنوان</th><th>PDF</th><th>صفحات پردازش‌شده</th><th>عملیات</th></tr></thead><tbody><?php foreach($books as $b):?><tr><td><?php echo esc_html($b->grade);?></td><td><?php echo esc_html($b->subject);?></td><td><?php echo esc_html($b->title);?></td><td><a href="<?php echo esc_url(wp_get_attachment_url($b->attachment_id));?>" target="_blank">مشاهده PDF</a></td><td><?php echo esc_html($b->page_count);?></td><td><a href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=hooshid_delete_book&id='.$b->id),'hooshid_delete_book'));?>" onclick="return confirm('حذف شود؟')">حذف</a></td></tr><?php endforeach;?></tbody></table></div><script>jQuery(function($){$('#hooshid-select-pdf').on('click',function(){var f=wp.media({title:'انتخاب کتاب PDF',button:{text:'انتخاب'},library:{type:'application/pdf'},multiple:false});f.on('select',function(){var a=f.state().get('selection').first().toJSON();$('#hooshid_attachment_id').val(a.id);$('#hooshid-pdf-name').text(a.filename||a.title);});f.open();});});</script><?php}
}